source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git', :branch => 'swift2.3'
pod 'BKMoneyKit', '0.0.8'

abstract_target 'BasePods' do
  target 'EurekaCreditCard_Example' do
    pod 'EurekaCreditCard', :path => '../'
  end

  target 'EurekaCreditCard_Tests' do
    pod 'EurekaCreditCard', :path => '../'

    pod 'FBSnapshotTestCase'
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '2.3'
        end
    end
end
